// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlqfroimdnzjexkiwvpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhscWZyb2ltZG56amV4a2l3dnBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjI4MjcsImV4cCI6MjA2NjQzODgyN30.ozlnk2SV8JvfOr4zWehhb3rzM5QKZICOAXtwSmN3YSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});